Shopify_sales data Analysis using SQL
DATABASE shopify_sales

CREATE TABLE shopify_sales (
    order_id TEXT,
    order_date DATE,
    customer_id TEXT,
    product_id TEXT,
    product_category TEXT,
    product_price NUMERIC,
    discount_percent NUMERIC,
    quantity INT,
    customer_country TEXT,
    traffic_source TEXT,
    payment_method TEXT,
    shipping_cost NUMERIC,
    rating NUMERIC,
    is_returned INT,
    discounted_price NUMERIC,
    revenue NUMERIC,
    profit NUMERIC
);
SELECT * FROM shopify_sales
----------------------------------------------------

Q1.Find total revenue and total profit.
SELECT
    SUM(revenue) AS revenue,
	SUM(profit)  AS profit
FROM shopify_sales;

Result:
Total Revenue : 59,645,935.58
Total Profit  : 58,834,630.10

Insight:

The business shows very high profitability, with profit nearly equal to revenue, 
indicating low operational costs or high-margin products.

Q2. Find the total number of orders and unique customers.
SELECT
COUNT(*) AS total_orders,
COUNT(DISTINCT customer_id)
FROM shopify_sales;

RESULT:
Total Order : 60000
Unique Customers: 31154

Insight:
The dataset contains 60,000 orders placed by multiple unique customers,
indicating a broad customer base and consistent transaction volume.

Q3.Find top 3 product categories by total revenue.

SELECT 
    product_category,
    SUM(revenue) AS total_revenue
FROM shopify_sales
GROUP BY product_category
ORDER BY total_revenue DESC
LIMIT 3;

Result:
Electronics :  8717301.49
Fashion     :  8609171.52
Home        :  8545840.45

Insight: highlighting key business segments driving overall sales.

 Q4: Calculate the total revenue generated by each country and rank them in descending order
SELECT 
    customer_country,
    SUM(revenue) AS total_revenue,
    RANK() OVER (ORDER BY SUM(revenue) DESC) AS country_rank
FROM shopify_sales
GROUP BY customer_country
ORDER BY total_revenue DESC;

Result:
 Country     Total Revenue     Rank
 Australia   8698940.71        1
 Germany     8566995.25        2
 UAE         8541233.92        3
 India       8509138.00        4
 Canada      8506629.46        5
 USA         8450978.82        6
 UK          8372019.42        7

Insight:
Australia leads in total revenue, followed by Germany and UAE, indicating strong 
performance in these regions. Revenue differences highlight market opportunities.

Q5. Find top 5 customers based on total spending.

SELECT 
    customer_id,
    SUM(revenue) AS total_spent
FROM shopify_sales
GROUP BY customer_id
ORDER BY total_spent DESC
LIMIT 5;

Result:
Customer id       Total Spent
40873	          12955.07
27889	          12462.80
15933	          11917.52
34270	          11654.95
24933	          11362.36

Insight:
A small group of customers contributes significantly to total revenue, 
indicating the presence of high-value customers important for business growth.

Q6: Calculate the average order value (AOV) across all orders

SELECT 
    ROUND(SUM(revenue) / COUNT(*), 2) AS average_order_value
FROM shopify_sales;

Result:
Average Order Value: 994.10

 Insight:
 The average order value indicates how much customers spend per order on average. 
 A higher AOV suggests strong purchasing behavior, while improving AOV can directly 
-- increase overall revenue.

Q7.Classify customers into High, Medium,and Low value based on total spending.

SELECT 
    customer_segment,
    COUNT(*) AS total_customers
FROM (
    SELECT 
        customer_id,
        CASE 
            WHEN SUM(revenue) > 10000 THEN 'High Value'
            WHEN SUM(revenue) BETWEEN 5000 AND 10000 THEN 'Medium Value'
            ELSE 'Low Value'
        END AS customer_segment
    FROM shopify_sales
    GROUP BY customer_id
) t
GROUP BY customer_segment;

Result:
   Customer_Segment    Total Customer   
  High Value             15
  Medium Value           29751
  Low Value              1388

 Insight:
 Customers are segmented based on their spending behavior. High-value customers 
 contribute the most to revenue and should be prioritized for retention strategies, 
 while medium and low-value customers offer opportunities for upselling and engagement.

Q9: Calculate monthly total revenue and sort it chronologically

SELECT 
    DATE_TRUNC('month', order_date) AS month,
    SUM(revenue) AS total_revenue
FROM shopify_sales
GROUP BY month
ORDER BY month;

Result:
Month        Total_Revenue
2023-01-01   2102673.23
2023-02-01   1872331.83
2023-03-01   2132980.04

 Insight:
The monthly revenue trend shows how sales change over time. 
This helps identify growth patterns, seasonal trends, and periods 
of high or low performance in the business.

Q10 Calculate month-over-month revenue growth (%)

SELECT 
    month,
    total_revenue,
    LAG(total_revenue) OVER (ORDER BY month) AS previous_month_revenue,
    ROUND(
        (total_revenue - LAG(total_revenue) OVER (ORDER BY month)) * 100.0 
        / LAG(total_revenue) OVER (ORDER BY month), 2
    ) AS growth_percentage
FROM (
    SELECT 
        DATE_TRUNC('month', order_date) AS month,
        SUM(revenue) AS total_revenue
    FROM shopify_sales
    GROUP BY month
) t
ORDER BY month;

 Result:
 Month       Revenue     Prev_Revenue   Growth(%)
2023-01      2102673.23      NULL           NULL
2023-02      1872331.83      2102673.23    -10.95
2023-03      2132980.04      1872331.83     13.92

 Q11. Identify the month with the highest total revenue

SELECT 
    month,
    total_revenue
FROM (
    SELECT 
        DATE_TRUNC('month', order_date) AS month,
        SUM(revenue) AS total_revenue
    FROM shopify_sales
    GROUP BY month
) t
ORDER BY total_revenue DESC
LIMIT 1;

 Result:
 Month        Total_Revenue
 2023-05-01   2142348.02

Insight:
The identified month generated the highest revenue, indicating peak business performance. 
This period may reflect seasonal demand, successful campaigns, or increased customer activity.

Q12: Calculate the overall return rate (%)

SELECT 
    ROUND(
        COUNT(*) FILTER (WHERE is_returned = 1) * 100.0 / COUNT(*), 
        2
    ) AS return_rate
FROM shopify_sales;

 Result:
 Return Rate: 14.81 %

Insight:
The overall return rate represents the percentage of orders that were returned. 
 A higher return rate may indicate issues with product quality, customer expectations, 
or delivery experience, and should be analyzed further.

Q12: Calculate the overall return rate (%)

SELECT 
    ROUND(
        COUNT(*) FILTER (WHERE is_returned = 1) * 100.0 / COUNT(*),
        2
    ) AS return_rate
FROM shopify_sales;

 Result:
 Return Rate: 14.81 %

Insight:
The overall return rate shows the percentage of orders that were returned. 
This metric helps evaluate product quality and customer satisfaction. 
A higher return rate may indicate issues that need business attention.

Q13. Calculate the return rate (%) for each product category

SELECT 
    product_category,
    COUNT(*) AS total_orders,
    COUNT(*) FILTER (WHERE is_returned = 1) AS returned_orders,
    ROUND(
        COUNT(*) FILTER (WHERE is_returned = 1) * 100.0 / COUNT(*),
        2
    ) AS return_rate
FROM shopify_sales
GROUP BY product_category
ORDER BY return_rate DESC;

 Result:
 Category       Total_Orders   Returned_Orders   Return_Rate
Sports           8522           1297               15.03
Fashion          8594           1292               15.01
Beauty           8586           1289               14.72
Footwear         8457           1245               14.65
Accessories      8617           1262               14.65
Electronics      8624           1262               14.63
Home Decor       8600           1240               14.42


 Insight:
 Return rates vary across product categories, with some categories showing 
 significantly higher returns. These categories may require quality checks, 
 better product descriptions, or improved customer expectations management.

 Q14. Identify product categories where return rate is higher than overall return rate

WITH overall_return AS (
    SELECT 
        COUNT(*) FILTER (WHERE is_returned = 1) * 100.0 / COUNT(*) AS overall_return_rate
    FROM shopify_sales
)

SELECT 
    product_category,
    COUNT(*) AS total_orders,
    COUNT(*) FILTER (WHERE is_returned = 1) AS returned_orders,
    ROUND(
        COUNT(*) FILTER (WHERE is_returned = 1) * 100.0 / COUNT(*),
        2
    ) AS return_rate
FROM shopify_sales, overall_return
GROUP BY product_category, overall_return_rate
HAVING 
    (COUNT(*) FILTER (WHERE is_returned = 1) * 100.0 / COUNT(*)) 
    > overall_return_rate
ORDER BY return_rate DESC;

Result:
 Category       Total_Orders   Returned_Orders   Return_Rate
 Sports           8522            1297             15.22
 Fashion          8594            1292             15.03
 Beauty           8586            1289             15.01

 Insight:
These categories have return rates higher than the overall average, 
indicating potential issues such as product quality concerns, mismatch in customer expectations, 
 

 Q15. Find the top-performing product category for each month based on revenue

SELECT 
    month,
    product_category,
    total_revenue
FROM (
    SELECT 
        DATE_TRUNC('month', order_date) AS month,
        product_category,
        SUM(revenue) AS total_revenue,
        RANK() OVER (
            PARTITION BY DATE_TRUNC('month', order_date) 
            ORDER BY SUM(revenue) DESC
        ) AS rank
    FROM shopify_sales
    GROUP BY month, product_category
) t
WHERE rank = 1
ORDER BY month;

 Result:
 Month        Category       Total_Revenue
 2023-01      Beauty        321759.84
 2023-02      Beauty        304383.63
-- ...

 Insight:
The top-performing category varies across months, indicating changing customer 
 preferences and seasonal demand.